as yet unclassified
getSampleJson
"sample data"
 ^ '[
  {
    "name": ".gitignore",
    "path": ".gitignore",
    "sha": "75272b234725a4c28072061be87f5885bfef9707",
    "size": 245,
    "url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/.gitignore?ref=master",
    "html_url": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/.gitignore",
    "git_url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/75272b234725a4c28072061be87f5885bfef9707",
    "download_url": "https://raw.githubusercontent.com/HPI-SWA-Teaching/SWT17-Project-13/master/.gitignore",
    "type": "file",
    "_links": {
      "self": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/.gitignore?ref=master",
      "git": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/75272b234725a4c28072061be87f5885bfef9707",
      "html": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/.gitignore"
    }
  },
  {
    "name": ".smalltalk.ston",
    "path": ".smalltalk.ston",
    "sha": "a4da76f0eb92f552e95565f5cc86a66c9de75afa",
    "size": 221,
    "url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/.smalltalk.ston?ref=master",
    "html_url": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/.smalltalk.ston",
    "git_url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/a4da76f0eb92f552e95565f5cc86a66c9de75afa",
    "download_url": "https://raw.githubusercontent.com/HPI-SWA-Teaching/SWT17-Project-13/master/.smalltalk.ston",
    "type": "file",
    "_links": {
      "self": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/.smalltalk.ston?ref=master",
      "git": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/a4da76f0eb92f552e95565f5cc86a66c9de75afa",
      "html": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/.smalltalk.ston"
    }
  },
  {
    "name": ".squot",
    "path": ".squot",
    "sha": "69d47d6c23aba8d670363a746ae50d359aad9d69",
    "size": 392,
    "url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/.squot?ref=master",
    "html_url": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/.squot",
    "git_url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/69d47d6c23aba8d670363a746ae50d359aad9d69",
    "download_url": "https://raw.githubusercontent.com/HPI-SWA-Teaching/SWT17-Project-13/master/.squot",
    "type": "file",
    "_links": {
      "self": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/.squot?ref=master",
      "git": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/69d47d6c23aba8d670363a746ae50d359aad9d69",
      "html": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/.squot"
    }
  },
  {
    "name": ".travis.yml",
    "path": ".travis.yml",
    "sha": "4d551854da03e7a61a73da8888c12870ef5ad897",
    "size": 196,
    "url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/.travis.yml?ref=master",
    "html_url": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/.travis.yml",
    "git_url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/4d551854da03e7a61a73da8888c12870ef5ad897",
    "download_url": "https://raw.githubusercontent.com/HPI-SWA-Teaching/SWT17-Project-13/master/.travis.yml",
    "type": "file",
    "_links": {
      "self": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/.travis.yml?ref=master",
      "git": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/4d551854da03e7a61a73da8888c12870ef5ad897",
      "html": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/.travis.yml"
    }
  },
  {
    "name": "LICENSE",
    "path": "LICENSE",
    "sha": "cd82761fccadaf7f61d4dcaaf54f89aa62f9225b",
    "size": 1093,
    "url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/LICENSE?ref=master",
    "html_url": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/LICENSE",
    "git_url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/cd82761fccadaf7f61d4dcaaf54f89aa62f9225b",
    "download_url": "https://raw.githubusercontent.com/HPI-SWA-Teaching/SWT17-Project-13/master/LICENSE",
    "type": "file",
    "_links": {
      "self": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/LICENSE?ref=master",
      "git": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/cd82761fccadaf7f61d4dcaaf54f89aa62f9225b",
      "html": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/LICENSE"
    }
  },
  {
    "name": "README.md",
    "path": "README.md",
    "sha": "49b859c40f9f8e9a3f89d3df6a87af7b53764f50",
    "size": 212,
    "url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/README.md?ref=master",
    "html_url": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/README.md",
    "git_url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/49b859c40f9f8e9a3f89d3df6a87af7b53764f50",
    "download_url": "https://raw.githubusercontent.com/HPI-SWA-Teaching/SWT17-Project-13/master/README.md",
    "type": "file",
    "_links": {
      "self": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/README.md?ref=master",
      "git": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/blobs/49b859c40f9f8e9a3f89d3df6a87af7b53764f50",
      "html": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/blob/master/README.md"
    }
  },
  {
    "name": "src",
    "path": "src",
    "sha": "5c282edae06597f36b9f179bf430b8c5b9bb027f",
    "size": 0,
    "url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/src?ref=master",
    "html_url": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/tree/master/src",
    "git_url": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/trees/5c282edae06597f36b9f179bf430b8c5b9bb027f",
    "download_url": null,
    "type": "dir",
    "_links": {
      "self": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/src?ref=master",
      "git": "https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/git/trees/5c282edae06597f36b9f179bf430b8c5b9bb027f",
      "html": "https://github.com/HPI-SWA-Teaching/SWT17-Project-13/tree/master/src"
    }
  }
]
'.