class initialization
initializeKeyLookupLinux
	^ (Dictionary newFrom:
		{1 -> Character escape.
		2 -> $1.
		3 -> $2.
		4 -> $3.
		5 -> $4.
		6 -> $5.
		7 -> $6.
		8 -> $7.
		9 -> $8.
		10 -> $9.
		11 -> $0.
		14 -> Character backspace.
		15 -> Character tab.
		16 -> $q.
		17 -> $w.
		18 -> $e.
		19 -> $r.
		20 -> $t.
		21 -> $y.
		22 -> $u.
		23 -> $i.
		24 -> $o.
		25 -> $p.
		28 -> Character cr.
		30 -> $a.
		31 -> $s.
		32 -> $d.
		33 -> $f.
		34 -> $g.
		35 -> $h.
		36 -> $j.
		37 -> $k.
		38 -> $l.
		44 -> $z.
		45 -> $x.
		46 -> $c.
		47 -> $v.
		48 -> $b.
		49 -> $n.
		50 -> $m.
		57 -> Character space.
		103 -> Character arrowUp.
		105 -> Character arrowLeft.
		106 -> Character arrowRight.
		108 -> Character arrowDown.
		})