"
Command that is put at the start of the LinkedList containing all commands for convenience
"
Class {
	#name : #GMTEPlaceHolderCommand,
	#superclass : #GMTECommand,
	#category : #'GM-TE-UI',
	#'squeak_changestamp' : 'Alex M 7/12/2024 22:22'
}

{
	#category : #execution,
	#'squeak_changestamp' : 'Alex M 7/12/2024 22:24'
}
GMTEPlaceHolderCommand >> do [
]

{
	#category : #execution,
	#'squeak_changestamp' : 'Alex M 7/12/2024 22:24'
}
GMTEPlaceHolderCommand >> undo [
]
