constants
testedKeys
	^ {{'backspace' . Character backspace}. {'tab' . Character tab}.
		{'enter' . Character cr}. {'escape' . Character escape}.
		{'space' . Character space}. {'arrowLeft' . Character arrowLeft}.
		{'arrowUp' . Character arrowUp}. {'arrowRight' . Character arrowRight}.
		{'arrowDown' . Character arrowDown}. {'0' . $0}.
		{'1' . $1}. {'2' . $2}. {'3' . $3}. {'4' . $4}. {'5' . $5}.
		{'6' . $6}. {'7' . $7}. {'8' . $8}. {'9' . $9}. {'a' . $a}.
		{'b' . $b}. {'c' . $c}. {'d' . $d}. {'e' . $e}. {'f' . $f}.
		{'g' . $g}. {'h' . $h}. {'i' . $i}. {'j' . $j}. {'k' . $k}.
		{'l' . $l}. {'m' . $m}. {'n' . $n}. {'o' . $o}. {'p' . $p}.
		{'q' . $q}. {'r' . $r}. {'s' . $s}. {'t' . $t}. {'u' . $u}.
		{'v' . $v}. {'w' . $w}. {'x' . $x}. {'y' . $y}. {'z' . $z}}